### ISSUE TITLE
Is setting max-width to img directly too opinionated?

### ISSUE THREAD

**Issue by austinstarin** [punkave/frontend-starter#10]
https://github.com/punkave/frontend-starter/blob/810d5c9e8dcbab927f28aeffe97c1baf840b8b6e/src/sass/base/_document.scss#L13

I wonder if we should handle this with utility classes.

**Comment by bgantick** [comment]
I'll go with whatever the group consensus is - I tend to forget to do this if it isn't automatically in place. I override where necessary (I find it rare that I don't want this set).

**Comment by austinstarin** [comment]
I end up having something like...

```css
.u-img-fluid { width: 100%; }
.u-img-max { max-width: 100% }
```

Or something similar.
